## NOTEBOOK 1


Please follow instructions below:

In [1]:
import numpy as np
import pandas as pd

 - Import IRIS dataset

In [2]:
from sklearn import datasets
iris = datasets.load_iris()

- Assign target (y) and  explanatory variables (X) from iris data

In [3]:
#:
X = iris.data
y = iris.target
X.shape

(150, 4)

- Split into test/train dataset

In [4]:
# Split into test/train dataset: test_size=0.3

from sklearn.model_selection import train_test_split
X_train,X_test, y_train,y_test = train_test_split(X, y,test_size=0.3)

- Creat logistic regression model

In [5]:
# Creat logistic regression model:

from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=100000)


- fit model on your data:

In [6]:
model.fit(X_train,y_train)

LogisticRegression(max_iter=100000)

 - Create predictions:

In [7]:
#Create predictions:
y_pred = model.predict(X_test)

 - print coefficients and intercept:

In [8]:
#print coefficients and intercept:

print(model.intercept_, model.coef_ )

[  8.85399743   2.44835972 -11.30235715] [[-0.40429441  0.80970946 -2.23516463 -0.86620534]
 [ 0.41567772 -0.51405912 -0.08774345 -0.80828373]
 [-0.01138331 -0.29565035  2.32290808  1.67448908]]


- check accuracy score

In [9]:
#check accuracy score
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.9777777777777777

## Accuracy measures

In [10]:
from sklearn.metrics import precision_score, recall_score, f1_score, classification_report

- print all accuracy measures:

In [11]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.95      0.97        19
           2       0.93      1.00      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45



## Regularization

 - Add regularization C=1 to the model

In [12]:
#Add regularization C=1


model = LogisticRegression(max_iter=100000,C=1)
model.fit(X_train,y_train)
print(accuracy_score(y_pred,y_test))


0.9777777777777777


 - import  and use scaler in pipeline

In [13]:
#import scaler:
from sklearn.preprocessing import StandardScaler

In [14]:
#Use in pipeline standarscaler:

from sklearn.pipeline import Pipeline


#?Pipeline

pipe = Pipeline([("standarization",StandardScaler()),("LogisticRegression",LogisticRegression(max_iter=100000,C=1))])

- fit the pipline

In [15]:
#Fit the pipe
pipe.fit(X_train,y_train)

Pipeline(steps=[('standarization', StandardScaler()),
                ('LogisticRegression',
                 LogisticRegression(C=1, max_iter=100000))])

- Check accuracy of model build with pipe

In [16]:
#Check accuracy of model build with pipe:
accuracy_score(pipe.predict(X_test), y_test)

0.9555555555555556

- Evaluate an accuracy score using Cross-validation on pipeline (use the cross_val_score function)

In [17]:
#Crossvalidate the accuracy of this pipeline (use the cross_val_score function)
from sklearn.model_selection import cross_val_score
cross_val_score(pipe, X,y, cv=10).mean()

0.9600000000000002

## GRID SEARCH

- Apply grid search to pipline using different grid parameters: 
param_grid = {
               "log_reg__penalty":["l2"],
               "log_reg__C":[0.1, 10,100]}

In [19]:
from sklearn.model_selection import GridSearchCV
pipe = Pipeline([("scale",StandardScaler()),("log_reg",LogisticRegression())])

param_grid = {
               "log_reg__penalty":["l2"],
               "log_reg__C":[0.01, 0.1,1, 10,100]}

gs = GridSearchCV(pipe,
                  param_grid,
                  cv = 10)

gs.fit(X,y)

GridSearchCV(cv=10,
             estimator=Pipeline(steps=[('scale', StandardScaler()),
                                       ('log_reg', LogisticRegression())]),
             param_grid={'log_reg__C': [0.01, 0.1, 1, 10, 100],
                         'log_reg__penalty': ['l2']})

- show the best grid parameters

In [20]:
gs.best_estimator_

Pipeline(steps=[('scale', StandardScaler()),
                ('log_reg', LogisticRegression(C=10))])

In [81]:
#END 